### ISSUE TITLE
Install error: Unrecognized command line option ‘-fcoroutines’

### ISSUE THREAD

**Issue by rbodo** [norse/aestream#29]
Hi,

I'm trying to install using pip (dependencies are there).

Compilation fails with the following errors:

>       c++: error: unrecognized command line option ‘-fcoroutines’
>       c++: error: unrecognized command line option ‘-std=c++20’; did you mean ‘-std=c++2a’?

I can get around the second one by following [these instructions](https://github.com/norse/aestream#setup-c) but the coroutines error persists.

I'm on Ubuntu 20.04 with gcc / g++ 10.3.

Thank you!

**Comment by rbodo** [comment]
Explicitly setting the compiler version did the trick, thank you so much Jens!

I'm at the [Telluride workshop](https://sites.google.com/view/telluride-2022/topic-areas/l2s-lifelong-learning-at-scale) right now where we are using your Durin robots in a continual learning setting. Excited to have this smooth setup now!

**Comment by Jegp** [comment]
Happy to help. I look forward to seeing what comes out of all the efforts!
