### ISSUE TITLE
Build error when using libcaer with enabled OpenCV support

### ISSUE THREAD

**Issue by emijan-kth** [norse/aestream#36]
If aestream is built using the libcaer library with enabled OpenCV support, the following compilation error occurs:

```
In file included from /usr/include/libcaercpp/devices/davis.hpp:4,
                 from /[...]/aestream-feature-cpp-nix/src/input/inivation.hpp:8,
                 from /[...]/aestream-feature-cpp-nix/src/aestream.cpp:16:
/usr/include/libcaercpp/events/frame.hpp:20:17: fatal error: opencv2/core.hpp: No such file or directory
   20 | #       include <opencv2/core.hpp>
      |                 ^~~~~~~~~~~~~~~~~~
```

One work-around for the error is to add the following section to `src/CMakeLists.txt`:

```
# OpenCV
find_package (OpenCV 4.0.0 REQUIRED)
include_directories(${OpenCV_INCLUDE_DIRS})
```

Another work-around is to instead add the following to `src/CMakeLists.txt`:

`add_definitions(-DLIBCAER_FRAMECPP_OPENCV_INSTALLED=0)`

**Comment by Jegp** [comment]
I've disabled OpenCV build at the moment. Please don't hesitate to reopen the issue if it persits.
